### ISSUE TITLE
GNUPG integration (mailvelope v3.0)

### ISSUE THREAD

**Issue by sbriskin** [mailvelope/mailvelope#628]
I have gnupg as a part of git for windows, but mailvelope thinks it's not installed. Is it possible to configure it?

**Comment by bernhardreiter** [comment]
@sbriskin what version of GnuPG do you have installed? 

For Window: try Gpg4win 3.1.5

For GNU systems: you shall have GPGME at least with version 1.12.0 from 2018-10-09.

**Comment by nagromc** [comment]
Don't know if it's the same problem, but in Mailvelope settings, the _Prefer GnuPG for all OpenPGP encryption operations_ option is not clickable, and _Not available_ is shown next to the option.

`gpg` works well inside a CLI though.

Please let me know if I should open another issue.

Mailvelope: v3.0.0
Gpg4win: v3.1.5 (installed with Chocolatey)
OS: Windows 10

**Comment by sbriskin** [comment]
@bernhardreiter 
Yes, with Gpg4win it works fine.
On linux i have
```
libgpgme11:
  Installed: 1.12.0-4
```
but that's not enough as i can see.

**Comment by bernhardreiter** [comment]
@nagromc 
I don't know if Chocolatey does something differently then a regular install. Maybe you can you try a regular install to verify this?

**Comment by sbriskin** [comment]
@bernhardreiter 
I'm using Debian Sid. libgpgme is not enough for mailvelope, so i built latest gpgme from sources and now it work fine.
But in my opinion this is too hard for ordinary user. Installing dev-tools and it's dependencies, node.js and it's dependancies just for one binary and one js lib - not a trivial task.

**Comment by rugk** [comment]
Yeah it obviously needs to be packaged by Linux distros…

**Comment by RoadRunnr** [comment]
very, very brief HOWTO for Chrome on GNU/Linux:

1. make sure you have gpgme 1.12.x and /usr/bin/gpgme-json installed. If your Linux distribution has an older gpgme or does not ship gpgme-json, you have to compile and install gpgme-json yourself,
2. get [gpgme-chrome.json](https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gpgme.git;a=blob_plain;f=doc/examples/gpgme-chrome.json;hb=HEAD) from the gpgme source,
3. copy gpgme-chrome.json to /etc/opt/chrome/native-messaging-hosts/gpgmejson.json

Restart Chrome and enjoy.

**Comment by nagromc** [comment]
> 
> 
> @nagromc
> 
> In the Gpg4win 3.1.5 installer, you need to actively select the GnuPG native messaging component for installation. My guess is that Chocolatey did only do the default install without it.

@bernhardreiter That's it. It is working as expected now. Many thanks.

**Comment by RoadRunnr** [comment]
@sbriskin 

> @bernhardreiter
> I'm using Debian Sid. libgpgme is not enough for mailvelope, so i built latest gpgme from sources and now it work fine.
> But in my opinion this is too hard for ordinary user. Installing dev-tools and it's dependencies, node.js and it's dependencies just for one binary and one js lib - not a trivial task.

There is no need to install node.js to build gpgme. node.js would only be needed to build the sample browser plugin, but all you need is gpgme-json and that builds fine with node.js.

**Comment by rugk** [comment]
> get gpgme-chrome.json from the gpgme source,

AFAIK these should be shipped with the distro package, should not they? Or with this add-on…?
Also for Firefox, l obviously…

**Comment by sbriskin** [comment]
> > @nagromc
> > In the Gpg4win 3.1.5 installer, you need to actively select the GnuPG native messaging component for installation. My guess is that Chocolatey did only do the default install without it.
> 
> @bernhardreiter That's it. It is working as expected now. Many thanks.

Not for me. I have tried to install it on my wife's notebook and got no luck at all.
Win10, Gpg4win 3.1.5 with browser integration selected. gpgme-json 1.12.1-beta43. Mailvelope 3.0.1. But "GnuPG is not available".

**Comment by nagromc** [comment]
@sbriskin 

> > > @nagromc
> > > In the Gpg4win 3.1.5 installer, you need to actively select the GnuPG native messaging component for installation. My guess is that Chocolatey did only do the default install without it.
> > 
> > 
> > @bernhardreiter That's it. It is working as expected now. Many thanks.
> 
> Not for me. I have tried to install it on my wife's notebook and got no luck at all.
> Win10, Gpg4win 3.1.5 with browser integration selected. gpgme-json 1.12.1-beta43. Mailvelope 3.0.1. But "GnuPG is not available".

Sometimes, I need to disable, and then, without restarting Firefox, re-enable the Mailvelope plug-in.

**Comment by nagromc** [comment]
> 
> 
> Overall I think we should consider closing this issue and open new ones that are more specific.
> Especially if we are talking initial set up, we should make a difference between Windows and GNU/Linux desktops.
> 
> @sbriskin Sorry to hear that is it not working for you, could you open a new issue and add the information about which browser you are trying in detail?
> 
> @nagromc So the support does stop working for you sometimes, but if it is enabled, it works?
> My suggestion is to open a new ticket with something like "Windows, Firefox, GnuPG integration sometimes needs to be re-enabled". Your problem seems different from those which do not get it enabled at all.

@bernhardreiter Yes. When it is enabled, it works. I will open a detailed issue if it occurs again.

**Comment by sbriskin** [comment]
@bernhardreiter i think it's a problem with my gpg4win installation on the notebook.
I close this issue for now.

**Comment by bernhardreiter** [comment]
@sbriskin @nagromc thanks for trying Mailvelope with GnuPG and for taking the time to give us this feedback! :)

**Comment by cryptoluks** [comment]
> very, very brief HOWTO for Chrome on GNU/Linux:
> 
>     1. make sure you have gpgme 1.12.x and /usr/bin/gpgme-json installed. If your Linux distribution has an older gpgme or does not ship gpgme-json, you have to compile and install gpgme-json yourself,
> 
>     2. get [gpgme-chrome.json](https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gpgme.git;a=blob_plain;f=doc/examples/gpgme-chrome.json;hb=HEAD) from the gpgme source,
> 
>     3. copy gpgme-chrome.json to /etc/opt/chrome/native-messaging-hosts/gpgmejson.json
> 
> 
> Restart Chrome and enjoy.

Just for completion for people using firefox you need to use this source:

[gpgmejson.json](https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gpgme.git;a=blob_plain;f=doc/examples/gpgme-mozilla.json;hb=HEAD)

Copy it to ~/.mozilla/native-messaging-hosts and restart mailvelope. It should work now.

**Comment by PoundXI** [comment]
> > very, very brief HOWTO for Chrome on GNU/Linux:
> > ```
> > 1. make sure you have gpgme 1.12.x and /usr/bin/gpgme-json installed. If your Linux distribution has an older gpgme or does not ship gpgme-json, you have to compile and install gpgme-json yourself,
> > 
> > 2. get [gpgme-chrome.json](https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gpgme.git;a=blob_plain;f=doc/examples/gpgme-chrome.json;hb=HEAD) from the gpgme source,
> > 
> > 3. copy gpgme-chrome.json to /etc/opt/chrome/native-messaging-hosts/gpgmejson.json
> > ```
> > Restart Chrome and enjoy.
> 
> Just for completion for people using Firefox you need to use this source:
> 
> [gpgmejson.json](https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gpgme.git;a=blob_plain;f=doc/examples/gpgme-mozilla.json;hb=HEAD)
> 
> Copy it to ~/.mozilla/native-messaging-hosts and restart Mailvelope. It should work now.

I download gpgme from https://gnupg.org/download/index.html#gpgme
Compile and install using ./configure ; make ; sudo make install
gpgme-json installed on /usr/local/bin/gpgme-json.

edit gpgmejson.json with "path": "/usr/local/bin/gpgme-json",
and copy it to ~/.mozilla/native-messaging-hosts/gpgmejson.json

But it not working. Mailvelop still showning message "GnuPG is not available".

[Ubuntu MATE 18.04 / Firefox 66 / gpg 2.2.4 / libgcrypt 1.8.1 / libgpgme11 (1.10.0-1ubuntu2)]

**Comment by PoundXI** [comment]
> > very, very brief HOWTO for Chrome on GNU/Linux:
> > ```
> > 1. make sure you have gpgme 1.12.x and /usr/bin/gpgme-json installed. If your Linux distribution has an older gpgme or does not ship gpgme-json, you have to compile and install gpgme-json yourself,
> > 
> > 2. get [gpgme-chrome.json](https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gpgme.git;a=blob_plain;f=doc/examples/gpgme-chrome.json;hb=HEAD) from the gpgme source,
> > 
> > 3. copy gpgme-chrome.json to /etc/opt/chrome/native-messaging-hosts/gpgmejson.json
> > ```
> > Restart Chrome and enjoy.
> 
> Just for completion for people using Firefox you need to use this source:
> 
> [gpgmejson.json](https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gpgme.git;a=blob_plain;f=doc/examples/gpgme-mozilla.json;hb=HEAD)
> 
> Copy it to ~/.mozilla/native-messaging-hosts and restart Mailvelope. It should work now.

Thank you for solution. It works on Ubuntu 18.04 with Firefox 66.0.

Here is full details for what I did.

Download **Libgpg-error** and **GPGME** source code from [https://gnupg.org/download/index.html](https://gnupg.org/download/index.html)

[Compile and install Libgpg-error >= 1.28]
$ tar xf libgpg-error-1.36.tar.bz2
$ cd libgpg-error-1.36
$ ./configure ; make ; sudo make install

[Compile and install GPGME with gpgme-json]
$ tar xf gpgme-1.13.0.tar.bz2
$ cd gpgme-1.13.0
$ ./configure ; make ; sudo make install

[Make gpgme-json available to Mailvelope on Firefox]
- Download [gpgmejson.json](https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gpgme.git;a=blob_plain;f=doc/examples/gpgme-mozilla.json;hb=HEAD)
- Edit path to **"path": "/usr/local/bin/gpgme-json",**
- Move gpgmejson.json to ~/.mozilla/native-messaging-hosts/gpgmejson.json
- Restart Firefox

**Comment by tomcastro89** [comment]
For Brave and Ubuntu you can use the same steps as described by @RoadRunnr :

> very, very brief HOWTO for Chrome on GNU/Linux:
> 
> make sure you have gpgme 1.12.x and /usr/bin/gpgme-json installed. If your Linux distribution has an older gpgme or does not ship gpgme-json, you have to compile and install gpgme-json yourself,
> get gpgme-chrome.json from the gpgme source,
> copy gpgme-chrome.json to /etc/opt/chrome/native-messaging-hosts/gpgmejson.json
> Restart Chrome and enjoy.

Note:
Do not install Brave via e.g. Snap. You will not be able to make it work.
Install Brave by following the steps here:
https://support.brave.com/hc/en-us/articles/360018666072-How-do-I-install-Brave-on-Linux-using-the-terminal-
Directory:
/home/{user}/.config/BraveSoftware/Brave-Browser/NativeMessagingHosts/gpgmejson.json
Content:
`{
    "name": "gpgmejson",
    "description": "Integration with GnuPG",
    "path": "/usr/local/bin/gpgme-json",
    "type": "stdio",
    "allowed_origins": [
        "chrome-extension://kajibbejlbohfaggdiogboambcijhkke/"
    ]
}`

**Comment by tprasadtp** [comment]
For those who wish to install without using `sudo`

- Download latest `libgpgerror` and `gpgme` and unpack them
- Build and install `libgpgerror`
  * `./configure --prefix=$HOME/.local`
  * `make && make install`
- Build and install `gpgme` while pointing to `ibgpgerror` libs and headers
  * ` export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/.local/lib`
  * ` export CPATH=$CPATH:$HOME/.local/include`
  * `./configure --prefix=$HOME/.local --with-libgpg-error-prefix=/home/prasad/.local/`
  * `make && make install`
- Make sure that `$HOME/.local/bin` is present in your PATH.
- Add `gpgmejson.json` to desired location after changing path to `gpgme-json` as indicated by 
`which gpgme-json`

You will need gpg2/gpg and gcc. If you are using yubikey, then you need to install scdaemon. these can be installed from system package manager. libgpgerror and gpgme provided by bionic are too old for mailvelope,

Tested on 18.04 bionic.

**Comment by rugk** [comment]
I wish to install it without having to self-compile anything… :roll_eyes:

**Comment by MattWThomas** [comment]
> I wish to install it without having to self-compile anything… roll_eyes

The `gpgme-json` package is not available on Ubuntu 20.04, but I was able to install this 20.10 version on the LTS release:
https://packages.ubuntu.com/groovy/gpgme-json
