### ISSUE TITLE
Mailvelope cannot find GnuPG with Browser Integration enabled

### ISSUE THREAD

**Issue by Q7ak5** [mailvelope/mailvelope#683]
GnuPG V2.2.15 with Gpg4Win V3.1.7 is installed, Browser Integration was enabled by installtion. It works fine, even with OpenPGP smart cards, so long as no Mailvelope is used. The current Mailvelope version (3.2.0) cannot find GnuPG: Options -> GnuPG is not available. This is definitely not true! Pressing button: "restart Mailvelope" does not solve the problem.

In Mailvelope I uploaded only my public key. So, I am able to encyrpt messages. But the private key is stored on the OpenPGP smart card only. If GnuPG is not recognized, the smart card cannot be found and decryption does not work. If I do not use Mailvelope my installation, including smart card is working fine. However, for de-mail the Mailvelope extension is mandatory and there I facing the problem described.

**Comment by MaximilianKrambach** [comment]
Hi,

I'm currently looking into this issue a bit, and I'm trying to write/collect information about the browser integration:
https://github.com/mailvelope/mailvelope/wiki/Debugging-gnupg-browser-integration

As I'm currently not on a native windows machine, debugging is a bit harder for me, so I'll appreciate feedback if there is something documentation-wise that could be improved (either in that text, or on the mailvelope or gpg4win side)

**Comment by Q7ak5** [comment]
Hi,

I did a research but I could not find anything useful. Why Mailvelope does not recognize GnuPG I cannot say. I believe this is the issue. Because GnuPG cannot be found, the smart card cannot work.

Normally I do not use Mailvelope, but it is a must for de-mail encryption with PGP. I can clearly say, that I can use my OpenPGP smart card in combination with GnuPG, Gpg4win and Outlook 2016. But if Mailvelope in de-mail is used, I face the problems described.

Because nearly nobody is using PGP in combination with de-mail, it is hard to find relevant information. This may explains why nothing can be found. If you check de-mail addresses, I am nearly the only one having a PGP key registered.

Best regards,

Juergen

-----Ursprüngliche Nachricht-----
Von: Maximilian Krambach <notifications@github.com> 
Gesendet: Montag, 20. Mai 2019 15:15
An: mailvelope/mailvelope <mailvelope@noreply.github.com>
Cc: Q7ak5 <Juerg_Walter@t-online.de>; Author <author@noreply.github.com>
Betreff: Re: [mailvelope/mailvelope] Mailvelope cannot find GnuPG with Browser Integration enabled (#683)

Hi,

I'm currently looking into this issue a bit, and I'm trying to write/collect information about the browser integration:
https://github.com/mailvelope/mailvelope/wiki/Debugging-gnupg-browser-integration

As I'm currently not on a native windows machine, debugging is a bit harder for me, so I'll appreciate feedback if there is something documentation-wise that could be improved (either in that text, or on the mailvelope or gpg4win side)

**Comment by JMRexach** [comment]
Hi Maximilian,

I've read de debug doc above and all conditions are meed. The 3 points mentioned at the end are satisfied. The id on Chrome and Mozilla matches. The cmd commands for gpgme-json.exe worked fine. The registry keys exist and points the .json files. But integration still doesn't work on Mailvelope 3.20.

Pls say me how can I help you more in depth. I'm using a native win 7 32 bit machine. I'm not a software expert/developer  so say me how to do it.

B.R.

Josep M. Rexach

**Comment by Q7ak5** [comment]
Hi,

I use Win 10, v1809, 64 bit. Mailvelope is working fine, so long as the entire keyring is stored in Mailvelope, I tested it. If I store only the public key in it and want to work with a OpenPGP smart card where the public key is stored, it fails because GnuPG is not recognized at all. 

I want to stress, that the OpenPGP smart card works fine without Mailvelope. For normal e-mails Mailvelope is not needed, but in case of De-mail Mailvelope is mandatory to apply PGP in de-mail.
A research from my site could not find any similar problems, because it is may a combination not often used. If you look in the de-mail addresses, PGP is very rarely used in de-mail. Most of the few which using PGP in de-mail will most likely not apply a smart card. So the topic is not surfaced so far.

**Comment by Q7ak5** [comment]
I was asking de-mail for advice. They called today back. They believe that Mailvelope should deal with it, because the problem seems to be there. They had no experience with using smart card so far for encryption. It would may best, if the Mailvelope developers could reproduce the case on their own machine. Of course I am willing to run also some tests, if I get advice, but I am not a software specialist.

**Comment by JMRexach** [comment]
Looking in detail the task mgr, I see that gpgme-json.exe starts as a process for a few seconds when I restart Mailvelope extension and then shuts down. Native messaging works fine on my Firefox because another extension (KeePassXC-Browser) works fine.

**Comment by Q7ak5** [comment]
In the task mgr, I cannot see gpgme-json.exe. I pressed Mailvelope restart and then I checked immediately task mgr again, no sign in the process list. I use Sticky Password in Firefox, it works fine. I assume native messaging should work.

**Comment by JMRexach** [comment]
In my case, I can see how gpgme-json.exe starts (remember to see all processes). Using procmon utility from Sysinternals suite, I obtained the log that I attach. I hope to be useful for developpers.
[Logfile.zip](https://github.com/mailvelope/mailvelope/files/3238147/Logfile.zip)

**Comment by Q7ak5** [comment]
Did you use an OpenPGP smart card in combination with Mailvelope? I checked with a second and a third computer. After I installed Mailvelope there. In all my computers, Mailvelope does not recognize that GnuPG is installed (but it is). On all computers the gpgme-json.exe is not shown in the task manager, if I press the "Mailvelope restart" button.

**Comment by JMRexach** [comment]
Hi,
I don't use smart cards with Gpg4win. But it seems to be a different behaviour between us. I can see for a few moments a process names gpgme-json in booth browsers. But the integration doesn't work.

**Comment by Q7ak5** [comment]
Hi,

I agree, because if I do not use smart card and store my keyring in mailvelope, it works fine. So, in this case OpenPGP.js is used and it seems to work. But the GnuPG integration has a bug. Hope, the developers can get to it soon. THANKS for your communications!

**Comment by Q7ak5** [comment]
The problem continuous with Gpg4win version 3.1.8, GnuPG version 2.2.16 and Mailvelope version 3.2.0. Still Mailvelope does not recognize the started GnuPG.

**Comment by JMRexach** [comment]
Something interesting:
This last week I moved to a new laptop. Win 10 64 bit I5, 8 Gb 1 Tb SSD. And mailvelope works fine with gpg4win on Mozilla and  Chrome. This laptop is faster, so this trouble can be performance related.

B.R.

JMa

**Comment by Q7ak5** [comment]
Certainly not a performance question. I face trouble with a HP ZBook 15u G5, 16GB RAM, Win 10, 64 bit. Gpg4win works fine indeed, the problem is the Mailvelope add-on. This add-on does not recognize that GnuPG is alreaday installed and asks therefore for installation. So long a Mailvelope does not recognize GnuPG, the OpenPGP smart card cannot be used in combination with Mailvelppe. This is my point. I have two more computer, the situation is always the same on all machines.

**Comment by MaximilianKrambach** [comment]
@Q7ak5 just out of curiosity, does your machine have SSD disks? I'm still trying to pin down the issue; and some parts of gpg4win are known for being a bit slow on windows file systems. So we might *just* run into a timeout here somewhere; while @JMRexach now passes that threshold with faster disks. It might be a matter of some hundred milliseconds or so.

**Comment by Q7ak5** [comment]
My main machine is a quite powerful HP ZBook 15u G5, with Intel i7-8550U CPU @ 1,85 GHz, with SSD and 16 GB RAM, so performance is no issue there. The two other machinces are Asus (little bit slower with HDD). On all three machines the current version is installed and "browser integration" was selected by installation. However, GnuPG is installed and it works fine with gpg4win, but Mailvelope fails to detect GnuPG. I am always asked to install it. I using Windows 10, 64 bit, version 1809, build 17763.503.

**Comment by Q7ak5** [comment]
May I should also mention that I tried Mailvelope in Firefox and Chrome. I deactivated all other add-ons, Mailvelope was the only active one. However, it failed in both browsers to detect GnuPG.

**Comment by JMRexach** [comment]
Hi,
In booth machines I've SSD disks. One works, and other no. The machine that doesn't work is a netbook with win7 starter, 2 Gb ram and SSD 512 Gb. It's really slow machine.

**Comment by JMRexach** [comment]
If any body has interested, I've a logfile obtained from a procmon utility (sysinternals). It's a large file (80 MB). If could be useful I can send it but tell me how. There you can see that gpgme-json.exe and forked processes of gnupg starts and finish. It covers firefox.exe and forked ones. It shows the disk activity and registry activity.

**Comment by MaximilianKrambach** [comment]
Hi @Q7ak5 @JMRexach , I would appreciate some feedback if the problem is solved for you as of mailvelope 3.3.1 (released end of last week, available from the official browser web stores/extension sites). It may need a browser restart after the extension update, but then it should work.

**Comment by JMRexach** [comment]
Hi Maximilian,
With new version 3.3.1 both browsers are still failing on my netbook machine.
Say me how can I help you.
JM

**Comment by Q7ak5** [comment]
Hi Maximilian,

Congratulation my problem is solved! I tested it today with a GnuPG smart card V3.3 with de-mail and with a GnuPG smart card version 2.2. with my e-mail provider. In both cases Mailvelope add-on worked seamless with GnuPG together and they recognized both cards. I sent and I received from both accounts encrypted e-mails (this was possible before), but I could also decrypt it (this was not possible before, because GnuPG was not reconized). Therefore, from my site the issue is successfully solved!

So, only the public key is stored in the Mailvelope add-on and the private key remains on smart card, as it should be. Easy to check, if your smart card is not inserted, decryption is not possible.

I have one advice for JMRexach: Please, check whether your Mailvelope does recognize GnuPG? If so, use as backend GnuPG and not OpenPG.js. This seems to be the default setting (at least in my case), I switched it to GnuPG and it worked! Obviously OpenPG.js, makes no sense for a setting where GnuPG is required. 

Maximilian, THANKS again for troublshooting!

**Comment by MaximilianKrambach** [comment]
> With new version 3.3.1 both browsers are still failing on my netbook machine.
> Say me how can I help you.
> JM

Hi @JMRexach ,
it's a bit of a hacky stretch, and I feel reluctant to suggest it, but we could try to manually increase the timeout even more on that machine, to see if it's just "even slower machine" or if I need to dig elsewhere.

**This will mess with the extension, and may break it** (if you try this and it fails, you may have to delete and reinstall mailvelope on chrome. GnuPG will not be affected)

1. The timeout until mailvelope gives up waiting for GnuPG is written in the mailvelope source code. In Chrome, it is possible to manually access this without too much gymnastics, it's just a bit hard to find. (For firefox, this would be more complicated)
2. For my machine, it is in `(Chrome config)/Default/Extensions/kajibbejlbohfaggdiogboambcijhkke/3.3.1_0/background.bundle.js`
3. I don't know if manually editing this file on Windows messes up things (e.g. line endings). So, maybe create a copy of it as backup.
4. At about line 93001, there is `GPGME_INIT_TIMEOUT = 3000;` If you change the 3000 to a higher number (e.g. 10000), mailvelope should be even more patient (we recently already increased the value)
5. Save the change, then restart chrome. If it works, we have the culprit.

**Comment by Q7ak5** [comment]
One comment for JMRexach: Did you install GnuPG with "Browser Integration" enabled? By default it is disabled. If you are not sure, deinstall GnuPG and reinstall it with the correct setting.

**Comment by JMRexach** [comment]
Hi Maximilian,

Many thanks for your time. Now I'm using a new I5 notebook and it works fine. I tried in my ols netbook with Chrome and modifiing up to 90000 still fails. So don't waste more time. I'll use in the new pc.

But I should notify the results of some tests done: I sent msg from Outlook using gpg4win 3.19. I send to 2 accounts in outlook.com and gmail.com from a third account. If I use (sign and encrypt) PGP/in-line booth works fine. But if I use attachment sending (not PGP/in-line) the behaviour changes: In gmail I can double click in the attached file and it opens Google-docs and decodes it. But in outlook.com I see the attachments but I'm unable to decode. If I save the attachment it seems a html code.
<img width="626" alt="Anotación 2019-07-10 190226" src="https://user-images.githubusercontent.com/50057117/60989748-fed63480-a346-11e9-96e1-86062599444e.png">

@Q7ak5 Thanks for your interest. Of course that integration was done. In fact I see how some processes json.exe start and then shutdown. But now I'm working with a new pc and it works fine. I'm happy that is solved also for you!

**Comment by MaximilianKrambach** [comment]
Hi @JMRexach ,
thanks for your help and time. I will take a note and maybe look into the failure again, but with lower priority.
For the other issue, I am clueless. But I suggest you open up a new issue, because here it probably will not be seen by other people.

**Comment by MaximilianKrambach** [comment]
(for cross-reference: the second issue is now #688 )

**Comment by HelmutFedder** [comment]
Any news on this? Just started using mailvelope and it does not find my Gpg4Win 3.1.11 (chrome and firefox). Since I also cant find a way to import my existing gpg key into mailvelope, this renders mailvelope unusable for me.

**Comment by Q7ak5** [comment]
My problem was already solved on July 8, 2019 as I wrote above. May you double check whether you ticked by installation of GnuPG the box: "Browser Integration"? If so, it should work. In my case I can use it in combination with OpenPGP smart card as well.

**Comment by HelmutFedder** [comment]
Reinstalling gpg4win with browser integration checked did the trick. Thank you very much for your valuable help.

**Comment by Q7ak5** [comment]
Perfect! One additional advice: If your private key is stored in mailvelope or another browser add-on it is generally exposed  to man-in-the-browser-attacks. May you consider OpenPGP smart card as storage decive for the private key. Then you copy only the public key to mailvelope. The the private key was generated on the smart card itself. If not in use it is air gapped and if in use the card is tampering proof. 

Of course you must invest in a card reader (cheap to expensive, but then with integrated firewall) and a smart card (search for OpenPGP smart card). With a modest investment you can add to your security and keed up your identity. However, the key must me generated on the card, it will be another key as you use at the moment. Generally you could copy your existing key to the card, but it is not best practice. The card is protected by a PIN and number of tries are limited. If you forget the PIN and reach the limit of wrong PIN number attempts the card will be blocked automatically.

So, make sure to know your PIN.

**Comment by gjf** [comment]
The key is Gpg4Win should be installed _after_ Mailvelope with browser integration checked.
Otherwise this integration won't be seen by Mailvelope and it cannot work with keys from OpenPGP.
So if you installed Gpg4Win before Mailvelope - just run installation process once again over it with all browser windows closed.
It works for me on my Chromium fork (Win 10 x64).

**Comment by valkum** [comment]
My comment in #725 might be interesting for this issue as well.
