### ISSUE TITLE
No keys found when GnuPG is correctly connected

### ISSUE THREAD

**Issue by YanzheL** [mailvelope/mailvelope#699]
# Description

I'm using GnuPG mode, and GnuPG connection is correctly set up.
But the Key Management tab is still empty, why?
I want to use keys in my native gnupg keyring, is that possible?

<img width="764" alt="Screen Shot 2019-08-17 at 17 53 20" src="https://user-images.githubusercontent.com/25402886/63209801-486d2880-c118-11e9-9fa2-65e071c0ac51.png">
<img width="1061" alt="Screen Shot 2019-08-17 at 17 53 29" src="https://user-images.githubusercontent.com/25402886/63209810-528f2700-c118-11e9-9dee-7ffb35f34a71.png">

# System Info

##### System

macOS 10.14.5

##### Browser

Chrome 77.0.3865.35 

##### Mailvelope Version
4.1.0

##### gpgme-tool
```
$ gpgme-tool
OK GPGME-Tool 1.13.1 ready
ENGINE
S ENGINE OpenPGP /usr/local/Cellar/gnupg/2.2.17/bin/gpg 2.2.17 1.4.0
S ENGINE CMS /usr/local/Cellar/gnupg/2.2.17/bin/gpgsm 2.2.17 2.0.4
S ENGINE GPGCONF /usr/local/bin/gpgconf 2.2.17 2.0.4
S ENGINE Assuan /Users/trinity/.gnupg/S.gpg-agent 1.0.0 1.0.0 !GPG_AGENT
S ENGINE UIServer /Users/trinity/.gnupg/S.uiserver 1.0.0 1.0.0
S ENGINE Spawn /nonexistent 1.0.0 1.0.0
OK
```

##### gpgme-json
```
$ gpgme-json --version
gpgme-json 1.13.1
Copyright (C) 2018 g10 Code GmbH
License LGPL-2.1-or-later <https://gnu.org/licenses/>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by YanzheL** [comment]
The native gnupg keyring contains lots of keys, because `gpg -k` and `gpg -K` have outputs.
So it's expected that Mailvelope's "Key Management" tab shows the same content.

**Comment by andrewgdotcom** [comment]
I have the same issue with the latest mailvelope plugin and a freshly compiled gpgme-1.13.1. `gpgme-json` works fine when invoked by hand:

```
$ echo '{"op":"keylist","secret":true}' | gpgme-json -s | jq .
{
  "keys": [
    {
      "revoked": false,
      "expired": false,
      "disabled": false,
      "invalid": false,
      "can_encrypt": true,
      "can_sign": true,
      "can_certify": true,
      "can_authenticate": true,
      "secret": true,
      "is_qualified": false,
      "protocol": "OpenPGP",
      "fingerprint": .....
```

Mailvelope refuses to accept that there are any keys, public or private.

**Comment by YanzheL** [comment]
@toberndo
Could you look into this? please...

**Comment by toberndo** [comment]
Please see https://github.com/mailvelope/mailvelope/wiki/Mailvelope-GnuPG-integration#macos-linux
Do you have the manifest file with the correct path to `gpgme-json` in your `NativeMessagingHosts`?

**Comment by andrewgdotcom** [comment]
Apologies, I should have mentioned that (unlike the OP) my error is experienced using Firefox 68.0.2-3 under Debian. And yes, I have the manifest correctly configured as in the link above.

**Comment by crookedstorm** [comment]
I also am following this because I have the same issue.  I have gpgme-json (compiled myself) and the file is present.  When these things were not true and correct, my client did not give me the option to select GnuPG.  It now does, but it cannot see any of my keys.  I am using MacOS 10.14.5 and Firefox.  I use GPG Suite for GnuPG (just FYI--not to start a big +1 thread).

**Comment by andrewgdotcom** [comment]
@crookedstorm I found exactly the same thing on Firefox/Linux so I doubt it's an OS- or browser-specific issue. I have a full normal GPG keyring for daily use and I manually imported my own public key to the mailvelope keyring in the browser. I don't see any option to switch keyrings in the mailvelope settings, just my lonely public key:

![image](https://user-images.githubusercontent.com/617742/64849550-8b34fa00-d60b-11e9-8988-6e1c32c27aa8.png)
![image](https://user-images.githubusercontent.com/617742/64849586-9d169d00-d60b-11e9-953a-20a4876a3752.png)

**Comment by toberndo** [comment]
Could you please check logging in the background page of the extension?
For Firefox:
- goto about:addons
- Settings Icon -> Debug Add-ons
- Mailvelope -> Inspect
- Switch to console tab

**Comment by crookedstorm** [comment]
I've got you some logs!
<img width="1433" alt="Screen Shot 2019-09-13 at 8 52 22 AM" src="https://user-images.githubusercontent.com/10637669/64876415-e82cb200-d603-11e9-9335-e16b7b69ac6f.png">

Anything you want me to expand or similar?

**Comment by crookedstorm** [comment]
In case it is at all helpful (considering the error message above), I also have:
$ gpgme-json --version
gpgme-json 1.13.1

@andrewgdotcom  Do you have the same (or similar) version?

**Comment by toberndo** [comment]
@crookedstorm Thanks! That brings us a step further.

@MaximilianKrambach @AndreHeinecke The error "Error exporting keys: Unsupported protocol" is raised at https://dev.gnupg.org/source/gpgme/browse/master/src/gpgme-json.c;b97434fbf087f3176daf39699ff579d38d265317$2696 when we call `gpgme.Keyring.getKeysArmored({with_secret_fpr: true})` in gpgme.js. Any ideas what could be the problem?

**Comment by toberndo** [comment]
Here are the options that I'm using for gpgme:
```
./configure --with-libassuan-prefix=/Users/toberndo/dev/gpgme/bin
--with-libgpg-error-prefix=/Users/toberndo/dev/gpgme/bin
--prefix=/Users/toberndo/dev/gpgme/bin
--enable-maintainer-mode
--enable-fixed-path=/usr/local/MacGPG2/bin
```
I think the `enable-fixed-path` option that contains the path to the gpg binary is important for our case when `gpgme-json` is called by the browser.

**Comment by crookedstorm** [comment]
I am sure I did not do that when I compiled.  While gpgme-json works fine on command line, I can imagine it could be something like that.  I'll recompile to check.

**Comment by crookedstorm** [comment]
I added that option to my configure (changing nothing else) and after restarting my browser:
<img width="317" alt="Screen Shot 2019-09-13 at 2 34 11 PM" src="https://user-images.githubusercontent.com/10637669/64896131-96038500-d633-11e9-8a17-9eafa3da17e6.png">

**Comment by andrewgdotcom** [comment]
@crookedstorm 
```
$ gpgme-json --version
gpgme-json 1.13.1
Copyright (C) 2018 g10 Code GmbH
License LGPL-2.1-or-later <https://gnu.org/licenses/>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

I'm going to try recompiling with those flags now.

**Comment by andrewgdotcom** [comment]
No joy for me I'm afraid. I tried `--enable-fixed-path=/usr/bin` and `--enable-fixed-path=/usr/bin/gpg` but neither helped.

**Comment by toberndo** [comment]
@andrewgdotcom Have you also used the `--enable-maintainer-mode` option?

**Comment by andrewgdotcom** [comment]
@toberndo yes, I tried that too.

I have a slightly different error message in the debug console though:

![image](https://user-images.githubusercontent.com/617742/65045277-6962ac80-d956-11e9-9c9c-4d0feb1b919c.png)

**Comment by andrewgdotcom** [comment]
@toberndo I've recompiled without any of the extra configure flags and I get the same error as above, so whatever I'm seeing it's a different issue than @crookedstorm is getting.

**Comment by AndreHeinecke** [comment]
regarding the build issues, can you do a "make check" in GPGME and it passes? There are some tests for gpgme-json under tests/json.

If they pass I would need a specific error from gpgme-json to help more. I can not really tell from the log you posted.

**Comment by jcostlow** [comment]
I am also having this probleml; GPG is installed, Mailvelope tells me that it can communicate with gpgme but I can see no keys from my keychain.


I am using a Mac. I have MacGPG installed. I used brew to install gpgme The two tools seem to interoperate just fine and I verified that /usr/local/Cellar/gnupg/bin/gpg (from brew) works correctly against my keychain.
I have followed the instructions in https://github.com/mailvelope/mailvelope/wiki/Mailvelope-GnuPG-integration
I can run `gpgme -i` and both version and keylist operations succeed and keys from my keychain are listed.
I am using Chrome.
Nothing shows up for me in the developer tools of Chrome, so I can't seem to debug that.

What is the next debugging step?

**Comment by ecky-l** [comment]
Exactly the same problem here, with macOS 10.15 Catalina and gnupg2, gpgme installed from macports. The Browser configuration and mailvelope extension installed as described in the wiki
[here](https://github.com/mailvelope/mailvelope/wiki/Mailvelope-GnuPG-integration), in Firefox as well as in Brave Browser. Both times the same result: GnuPG is found and can be selected as backend, but neither my gpg keys nor the keyring selection dropdown is available.

Please make this work. Mailvelope without GnuPG is not really an option for people like me, who want to use it with their yubikey...

**Comment by Nephirus** [comment]
I have the same issue on Windows, Gpg4win 3.1.10 (with Browser integration enabled) + Firefox. Mailvelope detects GnuPG, but I cannot switch keyring.
Extension debugger show this error:
```
Building keyring for id localhost|#|gnupg failed Error: "A connection timeout was exceeded."
    GPGME_Error moz-extension://4696e037-3b61-46ad-9297-df7b4d754c4b/background.bundle.js:79364
    gpgme_error moz-extension://4696e037-3b61-46ad-9297-df7b4d754c4b/background.bundle.js:79329
    post moz-extension://4696e037-3b61-46ad-9297-df7b4d754c4b/background.bundle.js:79804
background.bundle.js:86108:15
```

**Comment by mariusrugan** [comment]
i'm using MacOS Catalina, Chrome stable,

`brew install gpg`
`brew install gpgme`
json file is in place (~/Library/Application\ Support/Google/Chrome/NativeMessagingHosts/)
gpgme-json sees disk GnuPG keyring  (`echo '{"op":"keylist","secret":true}' | gpgme-json -s`)

Extension sees GnuPG keyring **ONLY** if Chrome is started from CLI.

**Comment by Frederick888** [comment]
I can confirm that Mailvelope in Firefox macOS also can talk to gpgme **only** if it's started from CLI. Not sure why this happens but I'm using KeePassXC, which has got a browser integration that works in a similar way, and it works without any issue.

Could this be related to macOS s*** like entitlements, code signing, etc? There have been quite a few changes in this area since 10.15 and they've managed to screwed up YubiKey PAM integration. What I've noticed in Console when I started Firefox from Launchpad/Dock/Spotlight:

> Prompting policy for hardened runtime; service: kTCCServiceAppleEvents requires entitlement com.apple.security.automation.apple-events but it is missing for ACC:{ID: org.mozilla.firefoxdeveloperedition, PID[48971], auid: 501, euid: 501, binary path: '/Applications/Firefox Developer Edition.app/Contents/MacOS/firefox'}, REQ:{ID: com.apple.appleeventsd, PID[317], auid: 55, euid: 55, binary path: '/System/Library/CoreServices/appleeventsd'}

There is no such warning in Console if Firefox is started from CLI. Could this be relevant?

**Comment by toberndo** [comment]
@mariusrugan @Frederick888 Please see my comment https://github.com/mailvelope/mailvelope/issues/699#issuecomment-531380721
Can you try to compile gpgme with these options instead of using brew?

**Comment by mariusrugan** [comment]
Sure, i glazed over those make params before and wasn't happy with enable
maintainer mode and didn't pay attention to the path one subsequently. :]

will do and report back.

**Comment by mariusrugan** [comment]
@toberndo yes, confirming it works, 
Chrome extension reads local keyring via locally compiled gpgme-json without using CLI start method of Chrome.

what i did:

**A. Try to compile gpgme-1.13.1 using brew installed lib dependencies** (/usr/local/Cellar/libgpg-error/1.36 & /usr/local/Cellar/libassuan/2.5.3). However ./configure step comes up with a platform warning. 
 GPGME v1.13.1  Platform:   x86_64-apple-darwin19.2.0 vs libgpg-error which is x86_64-apple-darwin19.2.2
So i've went down the road of everything compiled locally, just like your approach.

**B. Everything local:**
Downloaded libassuan-2.5.3; Unpacked and did:
./configure --prefix=/Users/myUser/Dev/lib/libassuan-2.5.3
make
make install

Downloaded libgpg-error-1.36; Unpacked and did:
./configure --prefix=/Users/myUser/Dev/lib/libgpg-error-1.36
make
make install

Downloaded gpgme-1.13.1; Unpacked and did:
./configure --prefix=/usr/local/share/gpgme-1.13.1 --enable-maintainer-mode --enable-fixed-path=/usr/local/MacGPG2/bin --with-libgpg-error-prefix=/Users/myUser/Dev/lib/libgpg-error-1.36 --with-libassuan-prefix=/Users/myUser/Dev/lib/libassuan-2.5.3
make
make install

Verified gpgme-json that it reads local keyring. 
echo '{"op":"keylist","secret":true}' | /usr/local/share/gpgme-1.13.1/bin/gpgme-json -s

Modified json (~/Library/Application\ Support/Google/Chrome/NativeMessagingHosts/gpgmejson.json)
path:
"path": "/usr/local/share/gpgme-1.13.1/bin/gpgme-json", 

Restarted Chrome, At first didn't see keyring; Restarted extension; 
In settings Which encryption backend do you prefer? GnuPG is selected. 
After a second browser restart extension sees keyring.

**Comment by Frederick888** [comment]
I can confirm compiling gpgme locally with `--enable-fixed-path` fixes the issue for Firefox as well.

By the way, I don't use MacGPG and I was able to recompile only gpgme itself. First make sure you've got `gnupg` `libgpg-error` `libassuan` etc all installed via Homebrew, then:

```sh
$ sudo mkdir /opt/gpgme
$ sudo chown $USER:staff /opt/gpgme
$ cd /tmp
$ wget https://github.com/gpg/gpgme/archive/gpgme-1.13.1.tar.gz
$ tar xvf gpgme-1.13.1.tar.gz
$ cd gpgme-1.13.1
$ ./autogen.sh
$ ./configure --enable-maintainer-mode --enable-fixed-path=/usr/local/bin --prefix=/opt/gpgme
$ make -j $(nproc) && make install
```
Finally update `~/Library/Application Support/Mozilla/NativeMessagingHosts/gpgmejson.json` to
```js
{
    "name": "gpgmejson",
    "description": "Integration with GnuPG",
    "path": "/opt/gpgme/bin/gpgme-json",
    "type": "stdio",
    "allowed_extensions": [
        "jid1-AQqSMBYb0a8ADg@jetpack"
    ]
}
```

**Comment by mariusrugan** [comment]
what are the correct settings for agent now @toberndo (also @Frederick888) to solve
"Inappropriate ioctl for device" error ?
Yesterday, while using the CLI method for Chrome, the error was related to timeout for inputing the password, i think. I had a prompt in the same terminal for it. 

I tried Password setting "Store in macOS Keychain" in GPG Suite settings without luck.

Also ~/.gnupg/gpg-agent.conf
allow-loopback-pinentry

Also in ~/.gnupg/gpg.conf
use-agent
pinentry-mode loopback
auto-key-retrieve

**Comment by Frederick888** [comment]
@mariusrugan IIRC you can opt out MacGPG during the installation of GPG Suite and GPG Keychain'll simply use the Homebrew one. Personally I've never been a fan of those bundled binaries as they often just complicate things.

**Comment by toberndo** [comment]
@mariusrugan @Frederick888 Many thanks for the descriptions! I added links to your comments to the wiki page (https://github.com/mailvelope/mailvelope/wiki/Mailvelope-GnuPG-integration)

**Comment by fionn** [comment]
Does it seem reasonable to make a PR for Homebrew to add `--enable-fixed-path=/usr/local/bin` to their `gpgme` formula?

**Comment by mariusrugan** [comment]
@fionn i think i would, but i don't know yet if `--enable-fixed-path=/usr/local/bin` is the only thing that makes this whole contraption work. -`-enable-maintainer-mode` is also needed. 

at a first glance , 
(https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gnupg.git;a=commit;h=2eee29253d5940e6da9cb2f44e9c44033675ec12) 
to me it looks like a "release / packaging" related flag, whereas previously i was thinking it would expose APIs that are security sensitive. 

didn't look in the formula yet also to see what's there.

maybe @toberndo  can comment on it ?

**Comment by toberndo** [comment]
Ping @AndreHeinecke @dd9jn for input on build flags for `gpgme`.

Here is the homebrew formula: https://github.com/Homebrew/homebrew-core/blob/master/Formula/gpgme.rb

**Comment by AndreHeinecke** [comment]
I don't think that we should solve it this way.

For Windows we have multiple ways to look for gpg binaries. On "Posix" which here means Linux and MacOS we only look at the PATH. So if GnuPG is not in the PATH it won't be found. With enable-fixed-path it can be forced to use that value instead.

Just compare:
https://dev.gnupg.org/source/gpgme/browse/master/src/w32-util.c;194272dbc3e326cc32c1464bc6fda0c0d10b5559$592

With:
https://dev.gnupg.org/source/gpgme/browse/master/src/posix-util.c;194272dbc3e326cc32c1464bc6fda0c0d10b5559$140

I think the best way to solve this, so that for example also a GnuPG installed by Gpgtools can be found would be to add fallbacks similar to the windows ones to posix util.

So please help me identify the cases that need to be covered:

Assuming that "gpg" is a binary in:

1. /usr/local/bin 
2. /usr/local/MacGPG2/bin
3. Relative to GPGME dynlib location ../bin

The 3. option should help when GPGME is installed in a custom location and then assumes that it is installed in the same prefix as gnupg.


I think that should cover it.

**Comment by AndreHeinecke** [comment]
Here is a patch that adds the /usr/local and /usr/local/MacGPG2 paths. Looking for the dynlib location was to complicated at a first glance (sorry I'm usually coding for Windows where there is API for that).

I have not tested / compiled this on and for Apple but it seems straightforward if I have no typos. Please give:
https://gist.github.com/AndreHeinecke/dc05bbf8c8aa89acd5d1e4b8f1d74e79

a test. @toberndo @mariusrugan
To test it compile GPGME with that patch and without the fixed-path option.

**Comment by toberndo** [comment]
@AndreHeinecke Looks good, I compiled without  `enable-fixed-path` on macOS and still the GnuPG from a GPGTools installation was found correctly.
Is `enable-maintainer-mode` required or recommended? If yes this would need to be added to the gpgme homebrew formula.

**Comment by AndreHeinecke** [comment]
I have pushed the change. enable-maintainer-mode is not required it only controls some internal autotools build system stuff and does not affect the behavior at runtime.

**Comment by dxdc** [comment]
@mariusrugan and others...

I struggled with these issues (macOS 10.14.6) and fixed them as follows without re-building any binaries:

1. Install gpg, gpgme with brew. 

```sh
brew install gpg
brew install gpgme
```

2. Re-link (if needed)

```sh
brew link --overwrite gnupg
brew link --overwrite gpgme
```

3. Add `~/Library/Application\ Support/Google/Chrome/NativeMessagingHosts/`

```js
{
    "name": "gpgmejson",
    "description": "Integration with GnuPG",
    "path": "/usr/local/bin/gpgme-json",
    "type": "stdio",
    "allowed_origins": [
        "chrome-extension://kajibbejlbohfaggdiogboambcijhkke/"
    ]
}
```

> At this stage, when launching `Chrome` from Terminal, I could see my keyring properly. However, when launching from the Dock, it failed. This (as others have pointed out) is due to the paths.

4. Update system and user paths to include `local` and restart your computer

```sh
sudo launchctl config user path /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
sudo launchctl config system path /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

**Comment by andrewgdotcom** [comment]
Interestingly, I went back into mailvelope for the first time in a while just there now, and it is magically working. I didn't change anything. Was there a code change in the plugin?

**Comment by AndreHeinecke** [comment]
As I was asked which commit was the change:
https://dev.gnupg.org/rM39052913f2154fa8e9575727e27d4101ef8b6460

It will be included in the next GPGME release. Which should happen in around a Months or so when we do our next Gpg4win release. When you then get that depends a bit on how you obtain GPGME on MacOS and when they will update.

**Comment by JokerQyou** [comment]
I think the homebrew version of gpgme formula (1.14) already contains the necessary changes, so a simple upgrading would do the trick.

**Comment by jcostlow** [comment]
Confirmed; `brew update ; brew upgrade` and it all works correctly for me. I may have had to restart Chrome, don't recall.

**Comment by regras** [comment]
I give up on Mailvelope. I tried everything suggested above in version 4.3.2 (including the compilation of gpgme with new configurations). Nothing seems to work here in MacOS 10.15.7, Firefox 82.0 or Chrome 86.0.4240.80, gpgme 1.14.0, gpg (GnuPG) 2.2.23,  libgcrypt 1.8.6 (these three installed with brew) even after uninstalling and reinstalling everything from scratch. Mailvelope (in Firefox or Chrome) cannot find my gpg keyring. If executed alone, gpgme-json can list the keys, but this is the farthest I could go.

**Comment by JokerQyou** [comment]
Anyway, if it helps, the last time I used Mailvelope it worked, the combination was:

- macOS `10.15.x` (it survived a minor OS update, so `x` does not matter)
- Edge (Chrome-based) with latest Mailvelope from Chrome store. Should also work with Chrome
- GPG Tools (GPG Suite `2020.1`) instead of GnuPG, manually installed
- gpgme `1.14` installed with homebrew

If you are using Chrome just follow the above comments. If you are using Edge then the native messaging file should be this `~/Library/Application Support/Microsoft Edge/NativeMessagingHosts/gpgmejson.json`. I've only tested in Edge stable.

**Comment by jimsiff2** [comment]
I was able to use the suggestion by @Frederick888 for GPG installed via MacPorts.  I kept the suggested /opt/gpgme path and symlinked the gpgme binaries from /opt/gpgme/bin/* to /opt/local/bin where the MacPorts binaries are installed.

**Comment by nottoseethesun** [comment]
Worked for me on Brave Browser, to sign mail, with vanilla Homebrew gpg, gpgme, and the `gpgmejson.json` file as listed above ( only replace path segments `/Google/Chrome/` with `/BraveSoftware/BraveBrowser/` )  - no `launchctl` or linking needed.  Note: I also do have the "GPG Keychain" macOS installed, since it was suggested by the Mailvelope website, but I don't think that is necessary.

**Comment by xpseudonym** [comment]
@andrewgdotcom if you're  listening - I wonder, are able to shed any more light on what happened 18 months or so ago?  (I realise you said nothing happened...)  I ask because I can see that the Debian packaging seems to have stalled after a lot of work by Sascha Wilde about a year ago for no apparent reason other than a lack of interest on the part of the Debian GnuPG packaging team: [src:gpgme1.0: please ship gpgme-json with native messaging hooks for chromium and firefox](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=911189#44)

So, I've installed the ubuntu build of `gpgme-json` - which looks like it should work:
```
:~$ sudo apt list *gpgme*
[sudo] password for readlegal: 
Listing... Done
golang-github-proglottis-gpgme-dev/byzantium 0.1.1-1 all
gpgme-json/now 1.14.0-1ubuntu3 amd64 [installed,local]
libgpgme-dev/byzantium 1.14.0-1+b2 amd64
libgpgme11/byzantium,now 1.14.0-1+b2 amd64 [installed,automatic]
libgpgmepp-dev/byzantium 1.14.0-1+b2 amd64
libgpgmepp-doc/byzantium 1.14.0-1 all
libgpgmepp6/byzantium,now 1.14.0-1+b2 amd64 [installed,automatic]
libqgpgme7/byzantium 1.14.0-1+b2 amd64
ruby-gpgme/byzantium 2.0.19-3+b3 amd64
```

(I'm running PureOS btw, which tracks Debian very closely:
```
:~$ uname -a
Linux mymachine 5.10.0-8-amd64 #1 SMP Debian 5.10.46-4 (2021-08-03) x86_64 GNU/Linux
```
)

I have no difficulty running `gpgme-json` manually as shown above:-
```
:~$ echo '{"op":"keylist","secret":true}' | gpgme-json -s | jq .
{
  "keys": [
    {
      "revoked": true,
      "expired": false,
      "disabled": false,
      "invalid": false,
      "can_encrypt": false,
      "can_sign": true,
      "can_certify": true,
      "can_authenticate": false,
      "secret": true,
      "is_qualified": false,
      "protocol": "OpenPGP",
      "fingerprint": "73A8EEC34FAF1B28226C36ABFB6547C4A9176094",
      "owner_trust": "unknown",
      "origin": 1,
      "last_update": 1613670531,
      "subkeys": [
        {
...
        {
          "revoked": false,
          "invalid": false,
          "validity": "ultimate",
          "uid": "Joe Blow (Joe Blow) <joe@blow.com>",
          "name": "Joe Blow",
          "email": "joe@blow.com",
          "comment": "Joe Blow, Joe Blow's House, UK",
          "address": "joe@blow.com",
          "origin": 0,
          "last_update": 0
        }
      ]
    }
  ]
}
```
But, still Mailvalope can 'see' GnuPG but the keys are not available:
![Screenshot from 2021-09-09 00-21-38](https://user-images.githubusercontent.com/5032475/132598147-0186d4a6-c9c9-446b-b413-a0f110c59efb.png)
![Screenshot from 2021-09-09 00-20-54](https://user-images.githubusercontent.com/5032475/132598151-8d04d626-1ef4-4954-b54c-91d528d48124.png)


If anyone else has any pointers, I've been thrashing about with this every now and again for a couple of years now and it would be really good to get it all working.  Many thanks.

**Comment by andrewgdotcom** [comment]
@xpseudonym Hi, Morgan. I'm afraid that after a few recent upgrades my Mailvelope is back to its old state as per comment https://github.com/mailvelope/mailvelope/issues/699#issuecomment-530918564 and the OP (i.e. I don't even get the dropdown menu to choose between the keyrings). I've been meaning to get back to debug it again...

**Comment by andrewgdotcom** [comment]
I'm now getting a novel error, even with the same gpgme-json that used to work:

```
Building keyring for id localhost|#|gnupg failed Error: A connection timeout was exceeded.
    GPGME_Error moz-extension://6f087239-1eed-4a93-b127-32f9cbe59074/background.bundle.js:56181
    gpgme_error moz-extension://6f087239-1eed-4a93-b127-32f9cbe59074/background.bundle.js:56146
    post moz-extension://6f087239-1eed-4a93-b127-32f9cbe59074/background.bundle.js:56621
```

The exact same happens in Firefox 78.13.0esr-1~deb11u1 on Bullseye, and 78.13.0esr-1~deb10u1 on Buster - both using Mailvelope 4.4.1. gpg is installed in the default /usr/bin/gpg on both.

(I recently upgraded my Mac and it deleted gpgme-json, so can't compare yet, will come back when I have something)

**Comment by andrewgdotcom** [comment]
After updating gpgme to v1.16 (hand-built from https://gnupg.org/download/index.html), and making sure to supply `--enable-maintainer-mode` to `./configure`, it works again for me. 

For the benefit of future archaeologists, I have also populated `~/.mozilla/native-messaging-hosts/gpgmejson.json` as follows:
```
{
    "name": "gpgmejson",
    "description": "Integration with GnuPG",
    "path": "/usr/local/bin/gpgme-json",
    "type": "stdio",
    "allowed_extensions": [
        "jid1-AQqSMBYb0a8ADg@jetpack"
    ]
}
```
This is the default from https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gpgme.git;a=blob_plain;f=doc/examples/gpgme-mozilla.json;hb=HEAD but with the path changed to /usr/local/bin as per my home-rolled install.

**Comment by xpseudonym** [comment]
> @xpseudonym Hi, Morgan. I'm afraid that after a few recent upgrades my Mailvelope is back to its old state as per comment [#699 (comment)](https://github.com/mailvelope/mailvelope/issues/699#issuecomment-530918564) and the OP (i.e. I don't even get the dropdown menu to choose between the keyrings). I've been meaning to get back to debug it again...

:o)))

> (I recently upgraded my Mac and it deleted gpgme-json, so can't compare yet, will come back when I have something)

Ah, good ol' Apple ay...

@andrewgdotcom [re your Comment above](https://github.com/mailvelope/mailvelope/issues/699#issuecomment-916334983)
So, it can work - thanks very much, perseverance is everything!  I'm just wondering what's  the difference between using a diy build and dropping in the Ubuntu package - I've nothing against building it myself except I'd like to be able to make this as painless as possible and understand why a build from Ubuntu doesn’t seem to work and a diy build does - why the Debian team hasn't been bothered reviewing Sascha's work is hard to understand.  I wonder if there's a difference because of the `--enable-maintainer-mode` flag?  What does it do?  If it's needed for Debian, wouldn't it also be for Ubuntu?  When you built yourself, did you install to `/usr/bin` or can it be installed to `/usr/local/bin` - I guess it's just a question of using the correct link in - ah, but wait for it - `gpgmejson.json` - I see looking at your  `gpgmejson.json`  code that you have installed to `/usr/local/bin`.

I found 'gpgmejson.json' already installed to the correct user location without me doing anything.  I wonder if it came with Firefox?  My Firefox is installed from Flathub, so perhaps it came with an update:
Mozilla Firefox Flatpak
mozilla-flatpak - 1.0
92.0 (64-bit)

**Comment by andrewgdotcom** [comment]
@xpseudonym Don't blame Apple - it was a hardware upgrade, and it was my own fault for forgetting to back up homebrew!

I'm beginning to think my particular problems may be down to gpgme being slow to respond on first invocation - whether from checking trustdb, or just parsing my stupidly large keyring I can't be sure. A couple of times now, across multiple machines, I've noticed that mailvelope seems unconfigured after starting up firefox, but disabling and re-enabling mailvelope in about:addons seems to kick it into life. This would be consistent with the "connection timeout" errors in the logs.

**Comment by andrewgdotcom** [comment]
I can confirm that `--enable-maintainer-mode` is a red herring (in my case at least). I rebuilt without it, restarted firefox, and got the usual failure. I then disabled and re-enabled mailvelope in about:addons and it mysteriously started working.

@xpseudonym do you have a particularly large keyring by any chance? Does the disable/enable trick work for you?

**Comment by andrewgdotcom** [comment]
I can further confirm that the ubuntu .deb package from https://packages.ubuntu.com/groovy/amd64/gpgme-json/download works for me on Debian bullseye - but again I had to disable and re-enable mailvelope in about:addons to get it to work. (NB the path had to be changed back to the default `/usr/bin/gpgme-json` in the native-messaging-hosts manifest)

**Comment by xpseudonym** [comment]
Okay, thanks @andrewgdotcom, Now, I've climbed back on to this old horse!
So, it seems that if you're running with the ubuntu package - then, I should be too...
It looks like the link you have corresponds to the package I've installed:
```
:~$ sudo apt list gpgme-json
Listing... Done
gpgme-json/now 1.14.0-1ubuntu3 amd64 [installed,local]
```
Would you mind just confirming the precise procedure you used to 'disable and re-enable mailvelope' ?
Thx

**Comment by andrewgdotcom** [comment]
On 13/09/2021 11:15, Morgan Read wrote:
> Would you mind just confirming the precise procedure you used to 
> 'disable and re-enable mailvelope' ?

Go to about:addons, click on mailvelope, and then use the toggle on the 
right, beside the three-dots menu.

-- 
Andrew Gallagher

**Comment by xpseudonym** [comment]
Okay, thanks @andrewgdotcom, Now, I've climbed back on to this old horse!
So, it seems that if you're running with the ubuntu package - then, I should be too...
It looks like the link you have corresponds to the package I've installed:
```
:~$ sudo apt list gpgme-json
Listing... Done
gpgme-json/now 1.14.0-1ubuntu3 amd64 [installed,local]
```
Would you mind just confirming the precise procedure you used to 'disable and re-enable mailvelope' ?
Thx

**Comment by andrewgdotcom** [comment]
I can now reproduce my error at will on both linux and mac, by swapping in one of two public keyring files - a small file with less than 10 keys works perfectly, while a large one with over a thousand causes startup issues (the above "connection timeout" error). Interestingly, the disable/enable trick works on linux, but doesn't (or at least, hasn't yet) worked on mac. The timeout is thrown approximately 5s after enabling the plugin, however it can take over 15s for my huge keyring to fully load, so it isn't simply a case of the call blocking until all records are returned.

**Comment by xpseudonym** [comment]
Well, I can't work it out...
![Screenshot from 2021-09-13 13-01-17](https://user-images.githubusercontent.com/5032475/133080196-67b9fa2f-c699-4397-bf29-10d1459249c0.png)
![Screenshot from 2021-09-13 13-02-33](https://user-images.githubusercontent.com/5032475/133080213-437ce3e8-a2b7-451a-9e20-458cc97c998c.png)

I'll have to do some more sleeping on this - just to confirm, I shouldn't be seeing this text:
> This keyring does not yet contain a key pair.
A key pair is required to encrypt and decrypt messages, as well as to invite your contacts to end-to-end encrypted communication.

And, I should be seeing something else?

**Comment by xpseudonym** [comment]
Oops, bump
Well, I've got 13 keys in my keyring...  according to `seahorse` - what file under `.gunpg` has the keyring - I've got a `.gnupg/pubring.gpg` at 12.2 MB and last modified 31.12.2017 - so, I'm not sure that's doing much - and I've got a `.gnupg/pubring.kbx` at 4.8 MB last modified 21.05.21 - which seems more relevant.

My `.gnupg` directory is probably over 15 years old by now...  Perhaps I'll delete it and start again?

**Comment by andrewgdotcom** [comment]
@xpseudonym pubring.kbx is the post-v2.1 standard keyring file, however if it is contains no keys then gnupg falls back on pubring.gpg. You can merge the two by following the "Convert an existing pubring.gpg file to the keybox format" instructions at https://www.gnupg.org/documentation/manuals/gnupg/GPG-Configuration.html

**Comment by NIRVANIAN472821** [comment]
Damnit, same problem here!

**Comment by xpseudonym** [comment]
@andrewgdotcom Belated thanks for pointer :smiley:

**Comment by andrewgdotcom** [comment]
Just pinging to see if there is any progress on this - there has been no update to the plugin since last year, and I can reproduce the connection timeout errors at will.

Would a reasonable workaround not be simply to increase the connection timeout when populating the keyring from gnupg?

**Comment by NoSubstitute** [comment]
I could connect gpgme-json using the manifest file, but getting this error when disable-enable the extension, and of course no keyring available.

Building keyring for id localhost|#|gnupg failed Error: Error exporting keys: Unsupported protocol
    at gpgme_error (background.bundle.js:79337:16)
    at Answer.getMessage (background.bundle.js:79886:29)
    at listener (background.bundle.js:79769:52)
DevTools failed to load source map: Could not load content for chrome-extension://kajibbejlbohfaggdiogboambcijhkke/browser-polyfill.js.map: System error: net::ERR_FILE_NOT_FOUND

***
$ gpgme-json --version
gpgme-json 1.18.0
Copyright (C) 2018 g10 Code GmbH
License GNU LGPL-2.1-or-later <https://gnu.org/licenses/>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

***
$ cat gpgmejson.json 
{
    "name": "gpgmejson",
    "description": "Integration with GnuPG",
    "path": "/opt/homebrew/bin/gpgme-json",
    "type": "stdio",
    "allowed_origins": [
        "chrome-extension://kajibbejlbohfaggdiogboambcijhkke/"
    ]
}

***
$ echo '{"op":"keylist","secret":true}' | gpgme-json -s | jq .
{
  "keys": [
    {
      "revoked": false,
      "expired": false,
      "disabled": false,
      "invalid": false,
      "can_encrypt": true,
      "can_sign": true,
      "can_certify": true,
      "can_authenticate": false,
      "secret": true,
      "is_qualified": false,
      "protocol": "OpenPGP",
      "fingerprint": "My Key Here",
      "owner_trust": "ultimate",
      "origin": 1,
      "last_update": 1649341334,
      "subkeys": [
        {

***
MBP, 2021, M1 Max
Ventura 13.2

**Comment by GwynethLlewelyn** [comment]
This is the _weirdest_ thing. Today, by sheer chance, I clicked on the Mailvelope icon on Brave (Version 1.47.186 Chromium: 109.0.5414.119) under macOS Big Sur (11.7.3 (20G1116)). To the best of my knowledge, nothing was changed: Mailvelope is still at version 4.7.1 (November 2022 version). gpg (GnuPG/MacGPG2) is still at 2.2.40.

And... it worked! It correctly found GnuPG and immediately allowed me to switch to that. And it was not just that: Gmail integration worked flawlessly, as well as... my own Roundcube installation (for several accounts and domains). _Everything_ worked (I needed to add API integration), like it _never_ worked before — I cannot even remember how long ago it was when I actually got _some_ of my accounts working, but never _all_ of them.

Microsoft Edge still seems to have a few hiccups; Firefox has no problems whatsoever (well, it almost never did); and I haven't got anything else installed to test with.

What I did? Nothing — I just happened to clean up the system (using [OnyX](https://titanium-software.fr/en/onyx.html)), rebooted the Mac, and that was it... it all started to work again.

This is _highly suspicious_ because most certainly it isn't easily reproducible, so I'm pretty sure that Mailvelope is not able to understand _why_ it stops working after a while — my best guess now is that there is some caching mechanism at the many levels (browser, extension, PGP...), and at some point, things just stop working of their own accord, without any _explicit_ reason for it. But nothing is truly _broken_ — it's just that a cleanup + restart will 'fix' (or rather, _reset_) whatever was blocking Mailvelope from contacting PGP and then it starts working again. At least for a while. Who knows?

**Comment by andrewgdotcom** [comment]
@GwynethLlewelyn in my experience this is a timeout issue, so your experience sounds consistent with mine - a freshly cleaned and rebooted system would presumably be faster to respond and less likely to time out.

If it does fail again in the future, check the error console to see if there is any log similar to the one I mentioned in https://github.com/mailvelope/mailvelope/issues/699#issuecomment-916030355

**Comment by GwynethLlewelyn** [comment]
> in my experience this is a timeout issue

That makes certainly a _lot_ of sense. It's a pity that we cannot get at least a small visual warning saying "connection timeout, please try again later!" :-)

**Comment by andrewgdotcom** [comment]
@GwynethLlewelyn not sure how useful that would be, because there's no way for the user to "try again later" without restarting the app, and in my case that just means I hit the timeout again... 🤪 

I stand by my proposal to increase the timeout. It's a one-character change...!

**Comment by andrewgdotcom** [comment]
Come on guys, the error is on `src/lib/browser.runtime.js` line 12. Don't make me fork the entire repo just so that I can PR an extra zero onto the default timeout value...!

**Comment by toberndo** [comment]
It‘s not that simple. The timeout blocks keyring initialization for the
majority of Mailvelope users who don‘t use GnuPG. The current value is a
tradeoff between waiting long enough to find GnuPG and not waiting too long
for all the others without GnuPG. Solution would be to load the keyrings
asynchronously.

**Comment by andrewgdotcom** [comment]
Surely there's a way to detect the presence or absence of GnuPG without waiting for a connection timeout?

**Comment by GwynethLlewelyn** [comment]
> Solution would be to load the keyrings asynchronously.

All right! There's your solution then :grin:

Alternatively: give some sort of _option_. You could have an 'advance mode' if you fear that regular users expect things to work 'automatically', and, by default, give them the _current_ behaviour. But add a checkbox for either longer timeouts; or a modal box saying, 'I've been waiting long enough, do you wish to continue to wait or abort?' and add twice the timeout before asking again (and so forth); or give them a checkbox for 'load keyrings asynchronously'.

I'd say that all of the above would be perfectly good suggestions, wouldn't break existing code and/or user expectations, while giving others the chance to extend their timeout to have Mailvelope catch up with whatever it's waiting for on GnuPG...

**Comment by toberndo** [comment]
Mailvelope [v5.0.0](https://github.com/mailvelope/mailvelope/releases/tag/v5.0.0) is out which defers loading of the GnuPG keyring and increases the GPGME timeout which should fix the problems related to loading large GnuPG keyrings in Mailvelope.

The GnuPG keyring is now only displayed in the Mailvelope keyring UI after it has been fully loaded and initialized. So for example if you restart Mailvelope or browser and quickly open the Mailvelope keyring UI, the GnuPG keyring might be missing. If you wait some more seconds and then refresh the keyring page it should appear.

v5.0.0 is already available in the Chrome Web Store. For Firefox we are still waiting for approval, but a test package is available at: https://download.mailvelope.com/releases/v5.0.0/

**Comment by steakknife** [comment]
> enable-maintainer-mode

[maintainer mode is a generic feature of automake](https://www.gnu.org/software/automake/manual/1.7.6/html_node/maintainer_002dmode.html)

**Comment by steakknife** [comment]
`curl -fsSL -o "$(brew --repository)/Library/Taps/homebrew/homebrew-core"/gpgme.rb https://gist.github.com/steakknife/ac4e437c87c81cdba3c595960d6ba3c6/raw/gpgme.rb && brew reinstall gpgme -s`

PSA: Friends don't let friends drink the Homebrew koolaid. Use a better package manager.

**Comment by andrewgdotcom** [comment]
Hi, Thomas.

Unfortunately while v5.0.1 is working on two of my three machines (one mac, one linux, both with small keyrings), I'm still seeing the gpgme connection timeout on the machine with the large keyring:

```
Building keyring for id localhost|#|gnupg failed Error: A connection timeout was exceeded.
    GPGME_Error moz-extension://1cc2e64c-8aa6-4444-86d2-23158c5f73c1/background.bundle.js:36418
    gpgme_error moz-extension://1cc2e64c-8aa6-4444-86d2-23158c5f73c1/background.bundle.js:36383
    post moz-extension://1cc2e64c-8aa6-4444-86d2-23158c5f73c1/background.bundle.js:36858
[background.bundle.js:87932:13](moz-extension://1cc2e64c-8aa6-4444-86d2-23158c5f73c1/background.bundle.js)
```

Waiting does not appear to help; I left my firefox running for several hours but still no sign of gpgme.

**Comment by huslage** [comment]
I realized that the file `~/Library/Application Support/Mozilla/NativeMessagingHosts/gpgmejson.json` is not included by default. I had to create it manually with the following contents after installing @steakknife formula. Now things are working in Firefox at least.

```
{
    "name": "gpgmejson",
    "description": "Integration with GnuPG",
    "path": "/opt/homebrew/bin/gpgme-json",
    "type": "stdio",
    "allowed_extensions": [
        "jid1-AQqSMBYb0a8ADg@jetpack"
    ]
}```

**Comment by andrewgdotcom** [comment]
I don't understand the reason for the timeout - if I call gpgme-json by hand and tell it to list my entire keyring of 719 keys, it takes less than a second:

```
andrewg@serenity ~ % echo '{"op":"keylist","public":true}' | time gpgme-json -s >/dev/null
gpgme-json -s > /dev/null  0.03s user 0.02s system 5% cpu 0.918 total
```

**Comment by bgiesing** [comment]
Having the same issues here on Pop_OS 22.04. I followed https://github.com/drduh/YubiKey-Guide to set up a GPG key on my YubiKey, Mailvelope is able to successfully connect (it shows the GnuPG dropdown option) but it says "This keyring does not yet contain a key pair." despite that gpgme command shared above and `gpg -k` showing my keys 

DevTools does show an error but no idea if this is why:
```
Error parsing armored GnuPG key: Error: readKeys: must pass options object containing `armoredKeys` or `binaryKeys`
    at readKeys (background.bundle.js:68390:11)
    at KeyStoreGPG.load (background.bundle.js:87665:20)
    at async buildKeyring (background.bundle.js:87973:3)
    at async initGPG (background.bundle.js:87927:5)
```

**Comment by andrewgdotcom** [comment]
Hi @bgiesing, I think this is a separate error from the one described above. That was due to a connection timeout, while yours appears to be an API usage error after successful connection.

**Comment by steakknife** [comment]
> I realized that the file `~/Library/Application Support/Mozilla/NativeMessagingHosts/gpgmejson.json` is not included by default. I had to create it manually with the following contents after installing @steakknife formula. Now things are working in Firefox at least.
> 
> ```
> {
>     "name": "gpgmejson",
>     "description": "Integration with GnuPG",
>     "path": "/opt/homebrew/bin/gpgme-json",
>     "type": "stdio",
>     "allowed_extensions": [
>         "jid1-AQqSMBYb0a8ADg@jetpack"
>     ]
> }
> ```

I don't use brew anymore. The homebrew core formula lacks the critical `--enable-fixed-path=` which is required for it to work anywhere other than the draconian default assumptions. Also, you have modified your system by giving one or all users access to `/opt/homebrew` which is a huge mistake.

**Comment by alexschrod** [comment]
I don't know if this will help anyone else, but I'll mention it nonetheless. I'm having issues with using GPG and Mailvelope together after my computer restarts (using Windows 10 and GPG4Win) *until* I take an action that activates my `gpg-agent`. I can do this either by using GPG manually outside of Mailvelope or by explicitly invoking the agent itself, but I find that Mailvelope only works when it's running.

As far as I can tell, this requirement of having `gpg-agent` running hasn't been documented anywhere, at least nowhere immediately visible, but it seems to be the truth for me at least.

**Comment by SBBH** [comment]
> I don't know if this will help anyone else, but I'll mention it nonetheless. I'm having issues with using GPG and Mailvelope together after my computer restarts (using Windows 10 and GPG4Win) _until_ I take an action that activates my `gpg-agent`. I can do this either by using GPG manually outside of Mailvelope or by explicitly invoking the agent itself, but I find that Mailvelope only works when it's running.
> 
> As far as I can tell, this requirement of having `gpg-agent` running hasn't been documented anywhere, at least nowhere immediately visible, but it seems to be the truth for me at least.

Thank you so much for this. When I first set Mailvelope up everything worked fine but after restarting my machine I was not able to get it working and I was getting really frustrated until I found your post. Thank you again!
